baseURL = "https://encuentroregionalifvp.github.io/"
languageCode = "es-mx"
title = "Encuentro Regional IFVP 2021"
theme = "minimal"
googleAnalytics = ""

[params]
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Inicio ğŸ "
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Â¿QuÃ© es? ğŸ¨"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "AcompÃ¡Ã±anos ğŸ‘ˆ"
    weight = 3
    title = "Que onda"

[[menu.main]]
    url = "/project/"
    name = "Sobre el encuentro ğŸ"
    weight = 4

